const serif = "'Source Serif 4', Georgia, serif";

export const S = {
  app: { maxWidth: 430, margin: "0 auto", minHeight: "100vh", background: "transparent", display: "flex", flexDirection: "column", position: "relative", overflowX: "hidden" },
  header: { position: "sticky", top: 0, zIndex: 100, background: "var(--header-bg)", backdropFilter: "blur(20px) saturate(1.6)", WebkitBackdropFilter: "blur(20px) saturate(1.6)", borderBottom: "1px solid var(--border-color)" },
  headerInner: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "14px 20px" },
  logo: { display: "flex", alignItems: "center", gap: 8 },
  logoIcon: { fontSize: 24, color: "#3D405B" },
  logoText: { fontSize: 20, fontWeight: 700, fontFamily: serif, color: "var(--text-primary)", letterSpacing: "-0.5px" },
  headerRight: { display: "flex", alignItems: "center", gap: 8 },
  langToggle: { display: "flex", background: "var(--lang-toggle-bg)", borderRadius: 8, padding: 2, border: "none", cursor: "pointer", gap: 0 },
  langOpt: { padding: "4px 10px", borderRadius: 6, fontSize: 12, fontWeight: 700, color: "var(--text-secondary)", transition: "all 0.2s", letterSpacing: 0.5 },
  langActive: { background: "var(--lang-active-bg)", color: "var(--lang-active-color)" },
  langDropBtn: { display: "flex", alignItems: "center", gap: 4, background: "var(--lang-toggle-bg)", border: "none", borderRadius: 8, padding: "5px 8px", cursor: "pointer", color: "var(--text-secondary)" },
  langDropMenu: { position: "absolute", top: "calc(100% + 6px)", right: 0, background: "var(--modal-bg)", backdropFilter: "blur(24px) saturate(1.6)", WebkitBackdropFilter: "blur(24px) saturate(1.6)", border: "1px solid var(--card-border)", borderRadius: 12, overflow: "hidden", zIndex: 300, minWidth: 140, boxShadow: "var(--card-shadow)" },
  langDropItem: { display: "flex", alignItems: "center", gap: 10, width: "100%", padding: "11px 14px", background: "none", border: "none", borderBottom: "1px solid var(--border-color)", cursor: "pointer", fontSize: 13, fontWeight: 500, color: "var(--text-primary)", textAlign: "left" },
  langDropItemActive: { background: "var(--tag-bg)", fontWeight: 600 },
  themeBtn: { background: "var(--lang-toggle-bg)", border: "none", borderRadius: 8, width: 34, height: 34, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "var(--text-secondary)", flexShrink: 0, transition: "background 0.2s" },
  notifBadge: { background: "none", border: "none", fontSize: 22, position: "relative", cursor: "pointer", padding: 4 },
  notifCount: { position: "absolute", top: -2, right: -4, background: "#E07A5F", color: "white", fontSize: 11, fontWeight: 700, borderRadius: 10, padding: "1px 6px", minWidth: 18, textAlign: "center" },
  main: { flex: 1, paddingBottom: 90 },
  sc: { padding: "16px 20px 20px" },
  heroCard: { background: "transparent", padding: "24px 0 20px", color: "var(--text-primary)", marginBottom: 16 },
  heroLabel: { fontSize: 14, fontWeight: 400, color: "var(--text-secondary)", marginBottom: 4 },
  heroAmount: { fontSize: 42, fontWeight: 700, fontFamily: serif, letterSpacing: "-1.5px", lineHeight: 1.1, color: "var(--text-primary)" },
  heroSub: { marginTop: 10 },
  escBadge: { background: "var(--tag-bg)", color: "var(--text-secondary)", fontSize: 13, fontWeight: 500, padding: "5px 12px", borderRadius: 20 },
  heroCredList: { margin: "16px 0 4px" },
  heroCredRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "6px 0", borderBottom: "1px solid var(--border-color)" },
  heroCredName: { fontSize: 13, fontWeight: 500, color: "var(--text-primary)" },
  heroCredAmt: { fontSize: 13, fontWeight: 700, fontFamily: serif, color: "var(--text-primary)" },
  heroDivider: { height: 1, background: "var(--border-color)", margin: "18px 0 14px" },
  heroStats: { display: "flex", justifyContent: "space-between" },
  heroStat: { textAlign: "center" },
  heroStatLabel: { fontSize: 12, color: "var(--text-secondary)", marginBottom: 4, fontWeight: 400 },
  heroStatVal: { fontSize: 18, fontWeight: 700, fontFamily: serif, color: "var(--text-primary)" },
  card: { background: "var(--card-bg)", backdropFilter: "var(--card-blur)", WebkitBackdropFilter: "var(--card-blur)", borderRadius: 16, padding: 20, marginBottom: 14, border: "1px solid var(--card-border)", boxShadow: "var(--card-shadow)" },
  cardTitle: { fontSize: 15, fontWeight: 700, fontFamily: serif, color: "var(--text-primary)", marginBottom: 14, letterSpacing: "-0.3px" },
  cardWarm: { background: "var(--warm-card-bg)", backdropFilter: "var(--card-blur)", WebkitBackdropFilter: "var(--card-blur)", borderRadius: 16, padding: 20, marginBottom: 14, border: "1px solid var(--warm-card-border)", boxShadow: "var(--card-shadow)" },
  cardSub: { fontSize: 13, color: "var(--text-secondary)", marginBottom: 14 },
  projRow: { display: "flex", gap: 6, marginTop: 12 },
  projPill: { flex: 1, textAlign: "center", background: "var(--tag-bg)", borderRadius: 10, padding: "8px 4px" },
  projPillL: { fontSize: 11, color: "var(--text-secondary)", fontWeight: 600, textTransform: "uppercase", letterSpacing: 0.5 },
  projPillV: { fontSize: 13, fontWeight: 700, color: "var(--text-primary)", marginTop: 2 },
  projPillD: { fontSize: 11, color: "#E07A5F", fontWeight: 600, marginTop: 1 },
  stageBar: { display: "flex", height: 18, borderRadius: 9, overflow: "hidden", marginBottom: 14 },
  stageSeg: { transition: "width 0.3s" },
  stageLegend: { display: "flex", flexDirection: "column", gap: 8 },
  stageLI: { display: "flex", alignItems: "center", gap: 10, fontSize: 13 },
  stageDot: { width: 12, height: 12, borderRadius: 6, flexShrink: 0 },
  stageLL: { fontWeight: 500, flex: 1 },
  stageLV: { color: "var(--text-secondary)", fontSize: 12 },
  stagePct: { fontSize: 11, fontWeight: 700, color: "var(--text-secondary)", background: "var(--tag-bg)", borderRadius: 6, padding: "2px 7px", marginLeft: 4 },
  bRow: { display: "flex", alignItems: "center", gap: 12, padding: "10px 0", borderBottom: "1px solid var(--border-color)" },
  bIcon: { fontSize: 24, width: 36, textAlign: "center" },
  bInfo: { flex: 1 },
  bLabel: { fontSize: 14, fontWeight: 500, marginBottom: 4 },
  bBarOut: { height: 6, background: "var(--tag-bg)", borderRadius: 3 },
  bBarIn: { height: 6, borderRadius: 3, transition: "width 0.4s" },
  bAmt: { fontSize: 15, fontWeight: 700, fontFamily: serif, whiteSpace: "nowrap" },
  urgRow: { display: "flex", alignItems: "center", gap: 12, padding: "10px 0", background: "none", border: "none", borderBottom: "1px solid var(--border-color)", width: "100%", cursor: "pointer", textAlign: "left" },
  urgDue: { fontSize: 12, color: "#E07A5F", fontWeight: 600 },
  alertBanner: { display: "flex", alignItems: "center", gap: 10, background: "var(--alert-banner-bg)", backdropFilter: "var(--card-blur)", WebkitBackdropFilter: "var(--card-blur)", border: "1px solid var(--alert-banner-border)", borderRadius: 12, padding: "14px 16px", marginTop: 8, cursor: "pointer", width: "100%", fontSize: 14, color: "var(--text-primary)", fontWeight: 500 },
  screenHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  screenTitle: { fontSize: 22, fontWeight: 700, fontFamily: serif, color: "var(--text-primary)" },
  addBtn: { background: "#3D405B", color: "white", border: "none", borderRadius: 10, padding: "9px 18px", fontSize: 14, fontWeight: 600, cursor: "pointer", boxShadow: "0 2px 8px rgba(61,64,91,0.25)", transition: "box-shadow 0.15s ease, transform 0.15s ease" },
  debtCard: { display: "flex", flexDirection: "column", background: "var(--card-bg)", backdropFilter: "var(--card-blur)", WebkitBackdropFilter: "var(--card-blur)", borderRadius: 14, padding: 16, marginBottom: 10, border: "1px solid var(--card-border)", borderLeft: "3px solid var(--border-color)", cursor: "pointer", width: "100%", textAlign: "left", boxShadow: "var(--card-shadow)" },
  dcRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 3 },
  dcName: { fontSize: 15, fontWeight: 600, color: "var(--text-primary)" },
  dcAmt: { fontSize: 16, fontWeight: 700, fontFamily: serif, flexShrink: 0, color: "var(--text-primary)" },
  dcNotes: { fontSize: 12, color: "var(--text-secondary)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", marginBottom: 8 },
  dcMeta: { display: "flex", alignItems: "center", gap: 8 },
  stagePill: { fontSize: 11, fontWeight: 600, padding: "3px 8px", borderRadius: 6 },
  dcDue: { fontSize: 12, color: "var(--text-secondary)" },
  backBtn: { background: "none", border: "none", fontSize: 15, color: "var(--text-secondary)", cursor: "pointer", marginBottom: 16, padding: 0, fontWeight: 500 },
  detailHdr: { textAlign: "center", marginBottom: 20 },
  detailName: { fontSize: 22, fontWeight: 700, fontFamily: serif, marginTop: 8, color: "var(--text-primary)" },
  detailAmt: { fontSize: 36, fontWeight: 700, fontFamily: serif, color: "#E07A5F", margin: "8px 0" },
  dRow: { display: "flex", justifyContent: "space-between", padding: "10px 0", borderBottom: "1px solid var(--border-color)", fontSize: 14 },
  dLabel: { color: "var(--text-secondary)", fontWeight: 500 },
  debtDetailHero: { textAlign: "center", marginBottom: 20, paddingBottom: 4 },
  detailHeroAmt: { fontSize: 42, fontWeight: 700, fontFamily: serif, color: "#E07A5F", margin: "6px 0 10px", letterSpacing: "-1px", lineHeight: 1.1 },
  docUploadBtn: { display: "block", width: "100%", padding: 12, background: "var(--tag-bg)", backdropFilter: "var(--card-blur)", WebkitBackdropFilter: "var(--card-blur)", border: "2px dashed var(--border-color)", borderRadius: 12, textAlign: "center", fontSize: 14, fontWeight: 600, color: "var(--text-primary)", cursor: "pointer", boxSizing: "border-box" },
  docTableHdr: { display: "flex", alignItems: "center", padding: "8px 0 6px", borderBottom: "2px solid var(--border-color)", fontSize: 11, fontWeight: 700, color: "var(--text-secondary)", textTransform: "uppercase", letterSpacing: 0.5, gap: 4 },
  docTableRow: { display: "flex", alignItems: "center", padding: "12px 0", borderBottom: "1px solid var(--border-color)", gap: 4 },
  deleteBtn: { width: "100%", background: "none", border: "1px solid #E07A5F", color: "#E07A5F", borderRadius: 12, padding: 14, fontSize: 15, fontWeight: 600, cursor: "pointer", marginTop: 20 },
  mailRow: { display: "flex", alignItems: "center", gap: 10, padding: "10px 0", borderBottom: "1px solid var(--border-color)" },
  mailDate: { fontSize: 12, color: "var(--text-secondary)", width: 50, flexShrink: 0 },
  mailSubj: { fontSize: 13, flex: 1, color: "var(--text-primary)" },
  statusDot: { width: 8, height: 8, borderRadius: 4, flexShrink: 0 },
  mailCard: { display: "block", background: "var(--card-bg)", backdropFilter: "var(--card-blur)", WebkitBackdropFilter: "var(--card-blur)", borderRadius: 14, padding: 16, marginBottom: 10, border: "1px solid var(--card-border)", borderLeft: "3px solid var(--border-color)", cursor: "pointer", width: "100%", textAlign: "left", boxShadow: "var(--card-shadow)" },
  mcTop: { display: "flex", alignItems: "center", gap: 8, marginBottom: 6 },
  mcCred: { fontSize: 14, fontWeight: 600, flex: 1, color: "var(--text-primary)" },
  mcDate: { fontSize: 12, color: "var(--text-secondary)" },
  mcSubj: { fontSize: 14, marginBottom: 8, lineHeight: 1.4, color: "var(--text-primary)" },
  mcBot: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  statusPill: { fontSize: 11, fontWeight: 600, padding: "3px 10px", borderRadius: 6 },
  mcAmt: { fontSize: 15, fontWeight: 700, fontFamily: serif, color: "var(--text-primary)" },
  typePill: { fontSize: 11, fontWeight: 600, padding: "3px 10px", borderRadius: 6 },
  // Advisor chat
  advisorWrap: { display: "flex", flexDirection: "column", height: "100%", minHeight: "calc(100vh - 110px)" },
  advisorHeader: { display: "flex", alignItems: "center", gap: 14, padding: "16px 20px 12px", borderBottom: "1px solid var(--border-color)" },
  advisorAvatar: { width: 44, height: 44, borderRadius: 22, background: "linear-gradient(135deg, #3D405B, #2A2D42)", color: "white", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, fontWeight: 700, flexShrink: 0 },
  advisorTitle: { fontSize: 17, fontWeight: 700, fontFamily: serif, color: "var(--text-primary)" },
  advisorSubtitle: { fontSize: 12, color: "var(--text-secondary)" },
  chatArea: { flex: 1, overflowY: "auto", padding: "16px 16px 8px" },
  welcomeMsg: { background: "var(--card-bg)", backdropFilter: "var(--card-blur)", WebkitBackdropFilter: "var(--card-blur)", borderRadius: 16, padding: "16px 18px", fontSize: 14, lineHeight: 1.5, color: "var(--text-primary)", border: "1px solid var(--card-border)", marginBottom: 14, boxShadow: "var(--card-shadow)" },
  chipsWrap: { display: "flex", flexDirection: "column" },
  chipsRow: { display: "flex", flexWrap: "wrap", gap: 8 },
  chip: { background: "var(--chip-bg)", backdropFilter: "var(--card-blur)", WebkitBackdropFilter: "var(--card-blur)", border: "1px solid var(--card-border)", borderRadius: 20, padding: "8px 16px", fontSize: 13, fontWeight: 500, color: "var(--text-primary)", cursor: "pointer", boxShadow: "var(--card-shadow)" },
  msgUser: { display: "flex", justifyContent: "flex-end", marginBottom: 12 },
  msgBot: { display: "flex", alignItems: "flex-start", gap: 8, marginBottom: 12 },
  msgBotAvatar: { width: 28, height: 28, borderRadius: 14, background: "#3D405B", color: "white", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 700, flexShrink: 0, marginTop: 2 },
  msgBubbleUser: { background: "#3D405B", color: "white", borderRadius: "18px 18px 4px 18px", padding: "12px 16px", maxWidth: "80%", fontSize: 14, lineHeight: 1.5 },
  msgBubbleBot: { background: "var(--card-bg)", backdropFilter: "var(--card-blur)", WebkitBackdropFilter: "var(--card-blur)", border: "1px solid var(--card-border)", borderRadius: "18px 18px 18px 4px", padding: "12px 16px", maxWidth: "85%", fontSize: 14, lineHeight: 1.5, color: "var(--text-primary)", boxShadow: "var(--card-shadow)" },
  thinkingDots: { display: "flex", gap: 5, padding: "4px 0" },
  dot: { width: 8, height: 8, borderRadius: 4, background: "var(--text-primary)", animation: "dotPulse 1.4s ease-in-out infinite" },
  chatInputWrap: { display: "flex", gap: 8, padding: "10px 16px 14px", borderTop: "1px solid var(--border-color)", background: "var(--nav-bg)", backdropFilter: "blur(20px) saturate(1.6)", WebkitBackdropFilter: "blur(20px) saturate(1.6)", flexShrink: 0 },
  chatInput: { flex: 1, padding: "12px 16px", border: "1px solid var(--input-border)", borderRadius: 24, fontSize: 15, background: "var(--input-bg)", backdropFilter: "var(--card-blur)", WebkitBackdropFilter: "var(--card-blur)", outline: "none", color: "var(--text-primary)" },
  sendBtn: { width: 44, height: 44, borderRadius: 22, background: "#3D405B", color: "white", border: "none", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  calLeg: { display: "flex", gap: 16, marginBottom: 14 },
  calLI: { display: "flex", alignItems: "center", gap: 6, fontSize: 13, color: "var(--text-secondary)" },
  calDot: { width: 8, height: 8, borderRadius: 4, display: "inline-block" },
  calGrid: { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", gap: 4 },
  calDay: { background: "var(--card-bg)", backdropFilter: "var(--card-blur)", WebkitBackdropFilter: "var(--card-blur)", borderRadius: 10, padding: "8px 4px", textAlign: "center", minHeight: 70, border: "1px solid var(--card-border)" },
  calToday: { border: "2px solid #3D405B", background: "var(--warm-card-bg)" },
  calDayNum: { fontSize: 13, fontWeight: 600, marginBottom: 4, color: "var(--text-primary)" },
  calDayDots: { display: "flex", justifyContent: "center", gap: 3, marginBottom: 2 },
  calDayAmt: { fontSize: 9, fontWeight: 600, color: "#E07A5F" },
  alertCard: { display: "flex", alignItems: "center", gap: 12, background: "var(--card-bg)", backdropFilter: "var(--card-blur)", WebkitBackdropFilter: "var(--card-blur)", borderRadius: 14, padding: 16, marginBottom: 10, border: "1px solid var(--card-border)", cursor: "pointer", width: "100%", textAlign: "left", boxShadow: "var(--card-shadow)" },
  alertText: { flex: 1, fontSize: 14, lineHeight: 1.4, color: "var(--text-primary)" },
  alertArrow: { color: "var(--text-secondary)", fontSize: 18 },
  empty: { textAlign: "center", padding: "40px 20px", fontSize: 16, color: "var(--text-secondary)" },
  fab: { position: "fixed", bottom: 80, right: 20, width: 56, height: 56, borderRadius: 28, background: "#3D405B", color: "white", border: "none", boxShadow: "0 4px 20px rgba(61,64,91,0.3)", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 50 },
  nav: { position: "fixed", bottom: 0, left: 0, width: "100%", background: "var(--nav-bg)", backdropFilter: "blur(20px) saturate(1.6)", WebkitBackdropFilter: "blur(20px) saturate(1.6)", borderTop: "1px solid var(--border-color)", display: "flex", padding: "8px 0 env(safe-area-inset-bottom, 8px)", zIndex: 100 },
  navBtn: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 2, background: "none", border: "none", cursor: "pointer", padding: "6px 0", color: "var(--text-secondary)", transition: "color 0.2s" },
  navBtnActive: { color: "var(--nav-active-color)" },
  navLabel: { fontSize: 11, fontWeight: 600 },
  modalOL: { position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "var(--modal-overlay)", zIndex: 200, display: "flex", alignItems: "flex-end", justifyContent: "center" },
  modal: { background: "var(--modal-bg)", backdropFilter: "blur(24px) saturate(1.6)", WebkitBackdropFilter: "blur(24px) saturate(1.6)", borderRadius: "24px 24px 0 0", width: "100%", maxWidth: 430, maxHeight: "92vh", overflowY: "auto", padding: "24px 20px 40px", border: "1px solid var(--card-border)", boxShadow: "var(--card-shadow)" },
  modalHdr: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20 },
  modalTitle: { fontSize: 20, fontWeight: 700, fontFamily: serif, color: "var(--text-primary)" },
  modalClose: { background: "none", border: "none", fontSize: 28, color: "var(--text-secondary)", cursor: "pointer", padding: 0, lineHeight: 1 },
  photoSec: { marginBottom: 20 },
  photoBtn: { width: "100%", padding: 16, background: "var(--tag-bg)", backdropFilter: "var(--card-blur)", WebkitBackdropFilter: "var(--card-blur)", border: "2px dashed var(--border-color)", borderRadius: 14, fontSize: 16, fontWeight: 600, color: "var(--text-primary)", cursor: "pointer" },
  photoDivider: { textAlign: "center", margin: "16px 0", fontSize: 13, color: "var(--text-secondary)" },
  fg: { marginBottom: 14 },
  fLabel: { display: "block", fontSize: 13, fontWeight: 600, color: "var(--text-secondary)", marginBottom: 6 },
  fInput: { width: "100%", padding: "12px 14px", border: "1px solid var(--input-border)", borderRadius: 10, fontSize: 15, background: "var(--input-bg)", backdropFilter: "var(--card-blur)", WebkitBackdropFilter: "var(--card-blur)", outline: "none", color: "var(--text-primary)" },
  fSelect: { width: "100%", padding: "12px 14px", border: "1px solid var(--input-border)", borderRadius: 10, fontSize: 15, background: "var(--input-bg)", backdropFilter: "var(--card-blur)", WebkitBackdropFilter: "var(--card-blur)", outline: "none", color: "var(--text-primary)" },
  fRow: { display: "flex", gap: 10 },
  submitBtn: { width: "100%", padding: 16, background: "#3D405B", color: "white", border: "none", borderRadius: 14, fontSize: 16, fontWeight: 700, cursor: "pointer", marginTop: 10 },
};
