const serif = "'Source Serif 4', Georgia, serif";

export const S = {
  app: { maxWidth: 430, margin: "0 auto", minHeight: "100vh", background: "var(--bg)", display: "flex", flexDirection: "column", position: "relative", overflowX: "hidden" },
  header: { position: "sticky", top: 0, zIndex: 100, background: "rgba(250,250,247,0.92)", backdropFilter: "blur(12px)", borderBottom: "1px solid var(--border-color)" },
  headerInner: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "14px 20px" },
  logo: { display: "flex", alignItems: "center", gap: 8 },
  logoIcon: { fontSize: 24, color: "#3D405B" },
  logoText: { fontSize: 20, fontWeight: 700, fontFamily: serif, color: "#3D405B", letterSpacing: "-0.5px" },
  headerRight: { display: "flex", alignItems: "center", gap: 10 },
  langToggle: { display: "flex", background: "#F0F0EB", borderRadius: 8, padding: 2, border: "none", cursor: "pointer", gap: 0 },
  langOpt: { padding: "4px 10px", borderRadius: 6, fontSize: 12, fontWeight: 700, color: "#6B7280", transition: "all 0.2s", letterSpacing: 0.5 },
  langActive: { background: "#3D405B", color: "white" },
  notifBadge: { background: "none", border: "none", fontSize: 22, position: "relative", cursor: "pointer", padding: 4 },
  notifCount: { position: "absolute", top: -2, right: -4, background: "#E07A5F", color: "white", fontSize: 11, fontWeight: 700, borderRadius: 10, padding: "1px 6px", minWidth: 18, textAlign: "center" },
  main: { flex: 1, paddingBottom: 90 },
  sc: { padding: "16px 20px 20px" },
  heroCard: { background: "linear-gradient(150deg, #FEF0E3 0%, #FAE6D0 100%)", borderRadius: 20, padding: "28px 24px 22px", color: "#2A1505", marginBottom: 16, boxShadow: "0 4px 20px rgba(180,100,50,0.10), 0 1px 4px rgba(180,100,50,0.07)" },
  heroLabel: { fontSize: 13, fontWeight: 500, color: "#B07848", textTransform: "uppercase", letterSpacing: 1.2, marginBottom: 4 },
  heroAmount: { fontSize: 38, fontWeight: 700, fontFamily: serif, letterSpacing: "-1px", lineHeight: 1.1, color: "#2A1505" },
  heroSub: { marginTop: 8 },
  escBadge: { background: "rgba(180,80,30,0.12)", color: "#B04820", fontSize: 12, fontWeight: 600, padding: "4px 10px", borderRadius: 8 },
  heroCredList: { margin: "16px 0 4px" },
  heroCredRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "6px 0", borderBottom: "1px solid rgba(150,90,40,0.10)" },
  heroCredName: { fontSize: 13, fontWeight: 500, color: "#4A2E10" },
  heroCredAmt: { fontSize: 13, fontWeight: 700, fontFamily: serif, color: "#2A1505" },
  heroDivider: { height: 1, background: "rgba(150,90,40,0.15)", margin: "18px 0 14px" },
  heroStats: { display: "flex", justifyContent: "space-between" },
  heroStat: { textAlign: "center" },
  heroStatLabel: { fontSize: 11, color: "#B07848", marginBottom: 2, textTransform: "uppercase", letterSpacing: 0.5 },
  heroStatVal: { fontSize: 18, fontWeight: 700, fontFamily: serif, color: "#2A1505" },
  card: { background: "var(--card-bg)", borderRadius: 16, padding: 20, marginBottom: 14, border: "1px solid var(--border-color)", boxShadow: "0 1px 3px rgba(0,0,0,0.05), 0 1px 2px rgba(0,0,0,0.03)" },
  cardTitle: { fontSize: 15, fontWeight: 700, fontFamily: serif, color: "var(--text-primary)", marginBottom: 14, letterSpacing: "-0.3px" },
  cardWarm: { background: "#FDFAF6", borderRadius: 16, padding: 20, marginBottom: 14, border: "1px solid #EDE8E0", boxShadow: "0 1px 3px rgba(0,0,0,0.04)" },
  cardSub: { fontSize: 13, color: "var(--text-secondary)", marginBottom: 14 },
  projRow: { display: "flex", gap: 6, marginTop: 12 },
  projPill: { flex: 1, textAlign: "center", background: "#F7F7F4", borderRadius: 10, padding: "8px 4px" },
  projPillL: { fontSize: 11, color: "var(--text-secondary)", fontWeight: 600, textTransform: "uppercase", letterSpacing: 0.5 },
  projPillV: { fontSize: 13, fontWeight: 700, color: "var(--text-primary)", marginTop: 2 },
  projPillD: { fontSize: 11, color: "#E07A5F", fontWeight: 600, marginTop: 1 },
  stageBar: { display: "flex", height: 18, borderRadius: 9, overflow: "hidden", marginBottom: 14 },
  stageSeg: { transition: "width 0.3s" },
  stageLegend: { display: "flex", flexDirection: "column", gap: 8 },
  stageLI: { display: "flex", alignItems: "center", gap: 10, fontSize: 13 },
  stageDot: { width: 12, height: 12, borderRadius: 6, flexShrink: 0 },
  stageLL: { fontWeight: 500, flex: 1 },
  stageLV: { color: "var(--text-secondary)", fontSize: 12 },
  stagePct: { fontSize: 11, fontWeight: 700, color: "var(--text-secondary)", background: "#F0F0EB", borderRadius: 6, padding: "2px 7px", marginLeft: 4 },
  bRow: { display: "flex", alignItems: "center", gap: 12, padding: "10px 0", borderBottom: "1px solid var(--border-color)" },
  bIcon: { fontSize: 24, width: 36, textAlign: "center" },
  bInfo: { flex: 1 },
  bLabel: { fontSize: 14, fontWeight: 500, marginBottom: 4 },
  bBarOut: { height: 6, background: "#F0F0EB", borderRadius: 3 },
  bBarIn: { height: 6, borderRadius: 3, transition: "width 0.4s" },
  bAmt: { fontSize: 15, fontWeight: 700, fontFamily: serif, whiteSpace: "nowrap" },
  urgRow: { display: "flex", alignItems: "center", gap: 12, padding: "10px 0", background: "none", border: "none", borderBottom: "1px solid var(--border-color)", width: "100%", cursor: "pointer", textAlign: "left" },
  urgDue: { fontSize: 12, color: "#E07A5F", fontWeight: 600 },
  alertBanner: { display: "flex", alignItems: "center", gap: 10, background: "#FFF3EB", border: "1px solid #F2CC8F", borderRadius: 12, padding: "14px 16px", marginTop: 8, cursor: "pointer", width: "100%", fontSize: 14, color: "#3D405B", fontWeight: 500 },
  screenHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  screenTitle: { fontSize: 22, fontWeight: 700, fontFamily: serif, color: "var(--text-primary)" },
  addBtn: { background: "#3D405B", color: "white", border: "none", borderRadius: 10, padding: "9px 18px", fontSize: 14, fontWeight: 600, cursor: "pointer", boxShadow: "0 2px 8px rgba(61,64,91,0.25)", transition: "box-shadow 0.15s ease, transform 0.15s ease" },
  debtCard: { display: "flex", flexDirection: "column", background: "var(--card-bg)", borderRadius: 14, padding: 16, marginBottom: 10, border: "1px solid var(--border-color)", borderLeft: "3px solid var(--border-color)", cursor: "pointer", width: "100%", textAlign: "left", boxShadow: "0 1px 3px rgba(0,0,0,0.05)" },
  dcRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 3 },
  dcName: { fontSize: 15, fontWeight: 600, color: "var(--text-primary)" },
  dcAmt: { fontSize: 16, fontWeight: 700, fontFamily: serif, flexShrink: 0 },
  dcNotes: { fontSize: 12, color: "var(--text-secondary)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", marginBottom: 8 },
  dcMeta: { display: "flex", alignItems: "center", gap: 8 },
  stagePill: { fontSize: 11, fontWeight: 600, padding: "3px 8px", borderRadius: 6 },
  dcDue: { fontSize: 12, color: "var(--text-secondary)" },
  backBtn: { background: "none", border: "none", fontSize: 15, color: "var(--text-secondary)", cursor: "pointer", marginBottom: 16, padding: 0, fontWeight: 500 },
  detailHdr: { textAlign: "center", marginBottom: 20 },
  detailName: { fontSize: 22, fontWeight: 700, fontFamily: serif, marginTop: 8 },
  detailAmt: { fontSize: 36, fontWeight: 700, fontFamily: serif, color: "#E07A5F", margin: "8px 0" },
  dRow: { display: "flex", justifyContent: "space-between", padding: "10px 0", borderBottom: "1px solid var(--border-color)", fontSize: 14 },
  dLabel: { color: "var(--text-secondary)", fontWeight: 500 },
  debtDetailHero: { textAlign: "center", marginBottom: 20, paddingBottom: 4 },
  detailHeroAmt: { fontSize: 42, fontWeight: 700, fontFamily: serif, color: "#E07A5F", margin: "6px 0 10px", letterSpacing: "-1px", lineHeight: 1.1 },
  docUploadBtn: { display: "block", width: "100%", padding: 12, background: "#F7F7F4", border: "2px dashed var(--border-color)", borderRadius: 12, textAlign: "center", fontSize: 14, fontWeight: 600, color: "#3D405B", cursor: "pointer", boxSizing: "border-box" },
  docTableHdr: { display: "flex", alignItems: "center", padding: "8px 0 6px", borderBottom: "2px solid var(--border-color)", fontSize: 11, fontWeight: 700, color: "var(--text-secondary)", textTransform: "uppercase", letterSpacing: 0.5, gap: 4 },
  docTableRow: { display: "flex", alignItems: "center", padding: "12px 0", borderBottom: "1px solid var(--border-color)", gap: 4 },
  deleteBtn: { width: "100%", background: "none", border: "1px solid #E07A5F", color: "#E07A5F", borderRadius: 12, padding: 14, fontSize: 15, fontWeight: 600, cursor: "pointer", marginTop: 20 },
  mailRow: { display: "flex", alignItems: "center", gap: 10, padding: "10px 0", borderBottom: "1px solid var(--border-color)" },
  mailDate: { fontSize: 12, color: "var(--text-secondary)", width: 50, flexShrink: 0 },
  mailSubj: { fontSize: 13, flex: 1 },
  statusDot: { width: 8, height: 8, borderRadius: 4, flexShrink: 0 },
  mailCard: { display: "block", background: "var(--card-bg)", borderRadius: 14, padding: 16, marginBottom: 10, border: "1px solid var(--border-color)", borderLeft: "3px solid var(--border-color)", cursor: "pointer", width: "100%", textAlign: "left", boxShadow: "0 1px 3px rgba(0,0,0,0.05)" },
  mcTop: { display: "flex", alignItems: "center", gap: 8, marginBottom: 6 },
  mcCred: { fontSize: 14, fontWeight: 600, flex: 1 },
  mcDate: { fontSize: 12, color: "var(--text-secondary)" },
  mcSubj: { fontSize: 14, marginBottom: 8, lineHeight: 1.4 },
  mcBot: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  statusPill: { fontSize: 11, fontWeight: 600, padding: "3px 10px", borderRadius: 6 },
  mcAmt: { fontSize: 15, fontWeight: 700, fontFamily: serif },
  typePill: { fontSize: 11, fontWeight: 600, padding: "3px 10px", borderRadius: 6 },
  // Advisor chat
  advisorWrap: { display: "flex", flexDirection: "column", height: "100%", minHeight: "calc(100vh - 110px)" },
  advisorHeader: { display: "flex", alignItems: "center", gap: 14, padding: "16px 20px 12px", borderBottom: "1px solid var(--border-color)" },
  advisorAvatar: { width: 44, height: 44, borderRadius: 22, background: "linear-gradient(135deg, #3D405B, #2A2D42)", color: "white", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, fontWeight: 700, flexShrink: 0 },
  advisorTitle: { fontSize: 17, fontWeight: 700, fontFamily: serif },
  advisorSubtitle: { fontSize: 12, color: "var(--text-secondary)" },
  chatArea: { flex: 1, overflowY: "auto", padding: "16px 16px 8px" },
  welcomeMsg: { background: "var(--card-bg)", borderRadius: 16, padding: "16px 18px", fontSize: 14, lineHeight: 1.5, color: "var(--text-primary)", border: "1px solid var(--border-color)", marginBottom: 14 },
  chipsWrap: { display: "flex", flexDirection: "column" },
  chipsRow: { display: "flex", flexWrap: "wrap", gap: 8 },
  chip: { background: "var(--card-bg)", border: "1px solid var(--border-color)", borderRadius: 20, padding: "8px 16px", fontSize: 13, fontWeight: 500, color: "#3D405B", cursor: "pointer" },
  msgUser: { display: "flex", justifyContent: "flex-end", marginBottom: 12 },
  msgBot: { display: "flex", alignItems: "flex-start", gap: 8, marginBottom: 12 },
  msgBotAvatar: { width: 28, height: 28, borderRadius: 14, background: "#3D405B", color: "white", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 700, flexShrink: 0, marginTop: 2 },
  msgBubbleUser: { background: "#3D405B", color: "white", borderRadius: "18px 18px 4px 18px", padding: "12px 16px", maxWidth: "80%", fontSize: 14, lineHeight: 1.5 },
  msgBubbleBot: { background: "var(--card-bg)", border: "1px solid var(--border-color)", borderRadius: "18px 18px 18px 4px", padding: "12px 16px", maxWidth: "85%", fontSize: 14, lineHeight: 1.5, color: "var(--text-primary)" },
  thinkingDots: { display: "flex", gap: 5, padding: "4px 0" },
  dot: { width: 8, height: 8, borderRadius: 4, background: "#3D405B", animation: "dotPulse 1.4s ease-in-out infinite" },
  chatInputWrap: { display: "flex", gap: 8, padding: "10px 16px 14px", borderTop: "1px solid var(--border-color)", background: "var(--bg)", flexShrink: 0 },
  chatInput: { flex: 1, padding: "12px 16px", border: "1px solid var(--border-color)", borderRadius: 24, fontSize: 15, background: "var(--card-bg)", outline: "none" },
  sendBtn: { width: 44, height: 44, borderRadius: 22, background: "#3D405B", color: "white", border: "none", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  calLeg: { display: "flex", gap: 16, marginBottom: 14 },
  calLI: { display: "flex", alignItems: "center", gap: 6, fontSize: 13, color: "var(--text-secondary)" },
  calDot: { width: 8, height: 8, borderRadius: 4, display: "inline-block" },
  calGrid: { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", gap: 4 },
  calDay: { background: "var(--card-bg)", borderRadius: 10, padding: "8px 4px", textAlign: "center", minHeight: 70, border: "1px solid var(--border-color)" },
  calToday: { border: "2px solid #3D405B", background: "#F7F7F4" },
  calDayNum: { fontSize: 13, fontWeight: 600, marginBottom: 4 },
  calDayDots: { display: "flex", justifyContent: "center", gap: 3, marginBottom: 2 },
  calDayAmt: { fontSize: 9, fontWeight: 600, color: "#E07A5F" },
  alertCard: { display: "flex", alignItems: "center", gap: 12, background: "var(--card-bg)", borderRadius: 14, padding: 16, marginBottom: 10, border: "1px solid var(--border-color)", cursor: "pointer", width: "100%", textAlign: "left", boxShadow: "0 1px 3px rgba(0,0,0,0.05)" },
  alertText: { flex: 1, fontSize: 14, lineHeight: 1.4 },
  alertArrow: { color: "var(--text-secondary)", fontSize: 18 },
  empty: { textAlign: "center", padding: "40px 20px", fontSize: 16, color: "var(--text-secondary)" },
  fab: { position: "fixed", bottom: 80, right: 20, width: 56, height: 56, borderRadius: 28, background: "#3D405B", color: "white", border: "none", boxShadow: "0 4px 20px rgba(61,64,91,0.3)", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 50 },
  nav: { position: "fixed", bottom: 0, left: "50%", transform: "translateX(-50%)", width: "100%", maxWidth: 430, background: "rgba(255,255,255,0.95)", backdropFilter: "blur(12px)", borderTop: "1px solid var(--border-color)", display: "flex", padding: "8px 0 env(safe-area-inset-bottom, 8px)", zIndex: 100 },
  navBtn: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 2, background: "none", border: "none", cursor: "pointer", padding: "6px 0", color: "var(--text-secondary)", transition: "color 0.2s" },
  navBtnActive: { color: "#3D405B" },
  navLabel: { fontSize: 11, fontWeight: 600 },
  modalOL: { position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "rgba(0,0,0,0.5)", zIndex: 200, display: "flex", alignItems: "flex-end", justifyContent: "center" },
  modal: { background: "var(--bg)", borderRadius: "24px 24px 0 0", width: "100%", maxWidth: 430, maxHeight: "92vh", overflowY: "auto", padding: "24px 20px 40px" },
  modalHdr: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20 },
  modalTitle: { fontSize: 20, fontWeight: 700, fontFamily: serif },
  modalClose: { background: "none", border: "none", fontSize: 28, color: "var(--text-secondary)", cursor: "pointer", padding: 0, lineHeight: 1 },
  photoSec: { marginBottom: 20 },
  photoBtn: { width: "100%", padding: 16, background: "#F7F7F4", border: "2px dashed var(--border-color)", borderRadius: 14, fontSize: 16, fontWeight: 600, color: "#3D405B", cursor: "pointer" },
  photoDivider: { textAlign: "center", margin: "16px 0", fontSize: 13, color: "var(--text-secondary)" },
  fg: { marginBottom: 14 },
  fLabel: { display: "block", fontSize: 13, fontWeight: 600, color: "var(--text-secondary)", marginBottom: 6 },
  fInput: { width: "100%", padding: "12px 14px", border: "1px solid var(--border-color)", borderRadius: 10, fontSize: 15, background: "white", outline: "none" },
  fSelect: { width: "100%", padding: "12px 14px", border: "1px solid var(--border-color)", borderRadius: 10, fontSize: 15, background: "white", outline: "none" },
  fRow: { display: "flex", gap: 10 },
  submitBtn: { width: "100%", padding: 16, background: "#3D405B", color: "white", border: "none", borderRadius: 14, fontSize: 16, fontWeight: 700, cursor: "pointer", marginTop: 10 },
};
